#!/usr/bin/env python3
"""Generate the final figure prompt JSON."""
import json

# Full prompt using Unicode smart quotes to avoid JSON escaping issues
prompt = (
    'A highly detailed, information-dense academic paper comprehensive analysis framework diagram '
    'in the style of top-tier management science and operations research publications. '
    'The diagram illustrates the product portfolio analysis based on the Boston Consulting Group (BCG) '
    'Matrix methodology, the 3-5-2 strategic realignment plan, packaging optimization comparison, '
    'and brand recognition enhancement through regional cultural design integration. '
    'The overall layout is arranged as a rich 2x2 four-panel grid with cross-panel connecting arrows '
    'forming a complete analytical chain from diagnosis to strategy to implementation to outcome measurement, '
    'with all figure labels and annotations rendered bilingually in English with Chinese parenthetical translations.\n\n'

    '=== PANEL A: BCG MATRIX PRODUCT PORTFOLIO ANALYSIS (TOP-LEFT) ===\n'
    'This panel presents a classic BCG Matrix 2x2 quadrant scatter plot. Set against a very faint grey '
    '#F7F7F7 background panel with a small-caps Steel Blue #0072B2 section label [BCG MATRIX ANALYSIS] '
    'at the top, separated by a thin grey #CCCCCC horizontal divider line. '
    'The horizontal x-axis is labeled [Relative Market Share (Low to High)] and the vertical y-axis '
    'is labeled [Industry Growth Rate (Low to High)], both rendered in Charcoal #333333 small annotation '
    'text at approximately 8pt, with Dark Grey #4D4D4D thin axis lines of 1px weight. '
    'The axes intersect at their midpoints, creating the classic four-quadrant structure divided by '
    'grey dashed crossing lines. The four quadrants are clearly labeled: top-left quadrant labeled '
    '[STARS: High Share x High Growth, less than 15 percent of total], top-right quadrant labeled '
    '[QUESTION MARKS: Low Share x High Growth, over 30 percent of total], bottom-left quadrant labeled '
    '[CASH COWS: High Share x Low Growth], and bottom-right quadrant labeled '
    '[DOGS: Low Share x Low Growth]. Each quadrant label is rendered in small-caps Charcoal #333333 text. '
    'Each quadrant uses an extremely subtle semi-transparent fill tint: the Stars zone receives a '
    '5 percent Warm Orange #E69F00 tint, the Question Marks zone receives a 5 percent Bluish Green #009E73 tint, '
    'while Cash Cows and Dogs zones remain pure white. Within each quadrant, a small monochrome icon '
    'thumbnail of approximately 15x15 pixels illustrates the category archetype: the Stars zone contains '
    'a small upward-trend arrow icon with a star symbol indicating dual high advantage, the Question Marks '
    'zone contains a small stylized question mark icon indicating strategic uncertainty, the Cash Cows zone '
    'contains a small stable horizontal bar chart thumbnail indicating steady profit contribution, and the '
    'Dogs zone contains a small downward-trend arrow icon with a flag indicating decline. '
    'The 42 product units are plotted as small filled-circle scatter points distributed across all four '
    'quadrants according to their market share and growth rate values. Stars products are plotted as small '
    'Warm Orange #E69F00 circles of 4px diameter, with a compact annotation reading [under 15 percent]. '
    'Question Marks products are plotted as small Bluish Green #009E73 circles, with annotation [over 30 percent]. '
    'Cash Cows products are plotted as Steel Blue #0072B2 circles, and Dogs products as Light Grey #CCCCCC circles. '
    'A small data summary annotation box in the bottom-right corner within this panel states in Medium Grey '
    '#666666 text at 7pt: [n equals 42 product units | Portfolio imbalance: Stars proportion insufficient, '
    'excessive Question Marks burden]. The quadrant boundary dashed lines extend slightly beyond the axes '
    'with small arrowheads.\n\n'

    '=== PANEL B: 3-5-2 STRATEGIC REALIGNMENT FLOW (BOTTOM-LEFT) ===\n'
    'This panel visualizes the strategic flow from BCG analytical findings to actionable portfolio restructuring. '
    'Set against a very faint grey #F7F7F7 background panel with a small-caps Steel Blue #0072B2 section label '
    '[STRATEGY REALIGNMENT: 3-5-2 PLAN] at the top, separated by a thin grey #CCCCCC divider line. '
    'The content is organized as three parallel vertical process columns arranged left-to-right, each representing '
    'one strategic bucket, connected by horizontal thin Steel Blue #0072B2 directional arrows of 1.5px weight.\n\n'

    'First column (leftmost): A white rectangular rounded-corner box with Steel Blue #0072B2 thin border of '
    '1.5px, top-labeled [STABILIZE] in Steel Blue small-caps text. Below the header, a prominent numerical badge '
    'in a Steel Blue circle reads [3 Products]. Inside the box body, three small monochrome abstract product '
    'icons are arranged vertically: a stable horizontal bar chart thumbnail, a steady-state sinusoidal waveform '
    'thumbnail with flat trendline, and a sustained growth arrow thumbnail at a moderate angle. Each icon has a '
    'tiny label [Profit Core] in 6pt Medium Grey. Below the icon stack, a strategy annotation reads '
    '[Retain 3 profit-contributing products to ensure cash flow stability] in Charcoal #333333 small text. '
    'A small currency symbol icon in Steel Blue sits at the bottom-right corner annotated [Ensure working capital turnover].\n\n'

    'Second column (center): A white rectangular rounded-corner box with Steel Blue #0072B2 thin border of '
    '1.5px, top-labeled [DEVELOP] in Steel Blue small-caps text. A prominent numerical badge in a Steel Blue '
    'circle reads [5 Products]. Inside the box body, five small product opportunity icons are arranged in a '
    'horizontal row, each marked with a small five-pointed star symbol rendered in Warm Orange #E69F00. '
    'Below the icon row, a resource allocation bar visualization is embedded: a horizontal stacked bar using '
    'Steel Blue #0072B2 segments of varying widths to represent concentrated resource investment, with each '
    'segment connected by a thin leader line to one of the five product icons. The strategy annotation reads '
    '[Concentrate resources on 5 high-potential products] in Charcoal #333333. A small upward growth curve '
    'thumbnail with accelerating trajectory is embedded at the box center-right annotated [Growth Trajectory]. '
    'A Warm Orange dashed outline sub-box highlights the resource concentration zones.\n\n'

    'Third column (rightmost): A white rectangular rounded-corner box with Light Grey #CCCCCC thin border of '
    '1px, top-labeled [PHASE OUT] in Medium Grey #666666 small-caps text. A prominent numerical badge in a '
    'Light Grey circle reads [2 Products]. Inside the box body, two small product icons are shown, each overlaid '
    'with a red Vermillion #D55E00 diagonal cross mark and a small descending trend line curve. The strategy '
    'annotation reads [Gradually eliminate 2 persistently underperforming categories] in Medium Grey #666666. '
    'A small downward arrow icon in Vermillion #D55E00 reinforces the phase-out concept.\n\n'

    'Flowing between columns: a Steel Blue arrow from column 1 to column 2 carries annotation '
    '[Capital freed for reinvestment]. Below all three columns, a grey dashed outline boundary box with Light '
    'Grey #CCCCCC stroke encloses the entire group with annotation [Strategic Objective: Optimize category '
    'portfolio structure through targeted 3-5-2 reallocation of 42 products]. A small input label at the left '
    'edge reads [Input: 42 Products from BCG Analysis] and a small output label at the right reads '
    '[Output: Optimized 10-Product Core Portfolio].\n\n'

    '=== PANEL C: PACKAGING OPTIMIZATION COMPARISON (TOP-RIGHT) ===\n'
    'This panel presents a rigorous side-by-side comparison of two packaging solutions with quantitative metrics. '
    'Set against a very faint grey #F7F7F7 background panel with a small-caps Steel Blue #0072B2 section label '
    '[PACKAGING OPTIMIZATION] at the top, separated by a thin grey #CCCCCC divider line.\n\n'

    'Left comparison box: A white rectangular box with Light Grey #CCCCCC thin border of 1px, top-labeled '
    '[Solution A: Standard Carton Packaging]. Embedded in the top-left interior is a small monochrome line-art '
    'thumbnail (approximately 30x30 pixel equivalent) of a standard corrugated cardboard box showing rectangular '
    'prism form with flap lines. Key pain point metrics displayed prominently: [Customer Complaint Rate: '
    'approximately 8 percent] in Vermillion #D55E00 bold text with a red cross mark icon, and '
    '[Cargo Damage Probability: High] also in Vermillion with a red cross. Two bullet-point annotations in '
    'Medium Grey #666666 enumerate pain points: [Damage during transit] and [Inconvenient opening mechanism], '
    'each with a small red Vermillion cross mark. At the bottom, a small damaged package icon (box with crack '
    'lines) reinforces the negative outcome.\n\n'

    'Right comparison box: A white rectangular box with Bluish Green #009E73 thin border of 1.5px, top-labeled '
    '[Solution B: EPP Cushioning plus Magnetic Buckle]. Embedded in the top-left interior is a small monochrome '
    'line-art thumbnail of EPP (Expanded Polypropylene) foam internal cushioning structure showing contoured '
    'protective buffer layers cradling a product shape. In the top-right interior, a second small detail '
    'thumbnail illustrates the magnetic buckle closure mechanism with interlocking magnetic elements. Key '
    'improvement metrics displayed prominently: [Cargo Damage Probability: approximately 2 percent] in Bluish '
    'Green #009E73 bold text with a green checkmark icon, accompanied by a green downward arrow annotation '
    '[reduced by 6 percentage points vs. Solution A]. Bullet-point annotations in Bluish Green list improvements: '
    '[Reduced transit damage] and [Magnetic buckle for easy opening], each with a green checkmark. At the '
    'bottom, a small intact package icon with visible magnetic closure detail reinforces the positive outcome.\n\n'

    'Between the two boxes, a horizontal bidirectional comparison arrow in Dark Grey #4D4D4D spans the gap, '
    'labeled [Packaging Upgrade] in 7pt text. Below both boxes, a comparison summary row displays four evaluation '
    'dimensions: [Cushion Material | Opening Mechanism | Damage Control | User Satisfaction], with green Bluish '
    'Green checkmarks under Solution B for all four dimensions and red Vermillion crosses under Solution A, '
    'creating a clear visual victory pattern.\n\n'

    '=== PANEL D: BRAND RECOGNITION ENHANCEMENT (BOTTOM-RIGHT) ===\n'
    'This panel quantifies the brand recognition impact of regional cultural design integration on packaging '
    'exteriors. Set against a very faint grey #F7F7F7 background panel with a small-caps Steel Blue #0072B2 '
    'section label [BRAND RECOGNITION IMPACT] at the top, separated by a thin grey #CCCCCC divider line.\n\n'

    'Top section: two side-by-side packaging exterior concept preview boxes. The left preview box has a Light '
    'Grey #CCCCCC border of 1px and contains a simplified monochrome line-art thumbnail of a generic, unadorned '
    'packaging exterior: a plain rectangular panel with no distinctive visual features, labeled [Before: Generic '
    'Design] below in 7pt Medium Grey. The right preview box has a Steel Blue #0072B2 border of 1.5px and '
    'contains a detailed monochrome line-art illustration thumbnail of the Broken Bridge with Remaining Snow '
    '(DuanQiao CanXue) cultural motif from Hangzhou West Lake Ten Scenes: an elegant arched stone bridge '
    'silhouette spanning a water surface, scattered snow patches as small white dots, delicate water ripples in '
    'simplified ink-painting (ShuiMo) style linework, and a subtle distant mountain silhouette. Below this box, '
    'a label reads [After: West Lake Broken Bridge Design] in Charcoal #333333, with a tiny annotation '
    '[Hangzhou Regional Identity Integration] in 6pt Medium Grey.\n\n'

    'Bottom section: A clean grouped bar chart for quantitative comparison of brand recognition. The chart has '
    'a subtle baseline horizontal axis in Dark Grey #4D4D4D and a vertical axis labeled [Brand Recognition '
    'Score]. Two vertical bars side by side: the left bar labeled [Before] in Light Grey #CCCCCC fill '
    'representing baseline brand recognition, and the right bar labeled [After] in Steel Blue #0072B2 fill '
    'reaching approximately 20 percent taller. At the top of the right bar, a prominent [+20 percent] annotation '
    'in bold Steel Blue. A graceful curved upward arrow in Warm Orange #E69F00 arcs from left bar top to right '
    'bar top with annotation [Brand recognition increased by approximately 20 percent, validated via visual '
    'tracking test]. Below the bar chart, a methodological footnote in 6pt Medium Grey reads: [Measurement '
    'method: Visual tracking test with consumer attention heatmap analysis]. A tiny thumbnail of a gaze heatmap '
    'overlay (showing concentrated warm-colored attention zones) is embedded next to the footnote.\n\n'

    '=== GLOBAL ANNOTATIONS AND CROSS-PANEL CONNECTIONS ===\n'
    'Strategic flow arrows connect the panels to show the analytical chain: A thick Steel Blue #0072B2 arrow '
    'flows from the right side of Panel A (from the Stars and Question Marks zones) to the left side of Panel B, '
    'carrying annotation [BCG finding drives strategy formulation]. A second arrow flows from Panel B (from the '
    'Stabilize column output) upward to the bottom of Panel C, labeled [Retained products receive packaging '
    'investment]. A third horizontal arrow connects Panel C to Panel D, labeled [Exterior design optimization '
    'enhances brand perception]. These three flow arrows create a clear diagnosis-to-outcome narrative thread.\n\n'

    'A comprehensive legend box is positioned in the absolute bottom-right corner of the entire figure, rendered '
    'as a white rounded-rectangle container with Light Grey #CCCCCC thin 1px border, titled [LEGEND] in '
    'small-caps Charcoal #333333 7pt text. Legend entries in two columns: left column lists scatter symbols '
    '(Orange filled circle for Stars under 15 percent, Green filled circle for Question Marks over 30 percent, '
    'Blue filled circle for Cash Cows, Grey filled circle for Dogs); right column lists annotation symbols '
    '(Green checkmark for Improved metric, Red cross mark for Pain point, Blue solid arrow for Strategic flow, '
    'Grey dashed outline for Objective boundary). All legend symbols at small scale with 6pt Medium Grey labels.\n\n'

    '=== STYLE SPECIFICATIONS ===\n'
    'Color palette: Okabe-Ito Academic Standard (colorblind-friendly, recommended by Nature, Science, and CVPR). '
    'Primary color Steel Blue #0072B2 used exclusively for core analytical module borders (Panels A, B section '
    'labels, Panel D right bar and preview box), primary data bars, and strategic flow arrows. Secondary color '
    'Warm Orange #E69F00 used exclusively for Stars category scatter markers, emphasis arrows, and percentage '
    'improvement annotation. Tertiary color Bluish Green #009E73 used exclusively for Question Marks scatter '
    'markers, optimized packaging solution borders (Panel C right box), and all positive metric annotations and '
    'checkmarks. Warning color Vermillion #D55E00 used extremely sparingly for pain point highlights (complaint '
    'rate, damage probability, phase-out indicators), appearing on fewer than 5 elements total. All module and '
    'content boxes use Pure White #FFFFFF fill with absolutely no colored fills anywhere. All section backgrounds '
    'use Faint Grey #F7F7F7. All primary text uses Charcoal #333333. All connection arrows, axis lines, divider '
    'lines, and boundary lines use Dark Grey #4D4D4D at 1px weight. Secondary and footnote text uses Medium Grey '
    '#666666 at 6-7pt equivalent. Standard non-emphasis box borders use Light Grey #CCCCCC at 1px. The figure '
    'contains zero colorful background panels, zero high-saturation banner bars, zero gradients, zero rainbow or '
    'multi-hue effects. All modules follow white fill with colored or grey thin borders (1-1.5px): color conveyed '
    'exclusively through border strokes, never fill. Section partitioning uses small-caps text labels with thin '
    'grey horizontal divider lines. All embedded thumbnails and icons are monochrome or two-color line drawings '
    '(grey base with single accent color where semantically appropriate). At least 70 percent of surface area is '
    'white or near-white. The figure must remain fully legible when printed in grayscale: all critical information '
    'conveyed through shape, spatial position, text labels, and line weight variation. No ellipsis or etc. used '
    'to summarize. Figure dimensions: 16:9 aspect ratio, suitable for A4 or US Letter full-width column at '
    'minimum 300 DPI resolution.'
)

figure = {
    "figure_number": "1",
    "figure_title_cn": "产品组合波士顿矩阵分析与包装优化综合框架",
    "figure_title_en": "BCG Matrix Product Portfolio Analysis and Packaging Optimization Framework",
    "figure_type": "综合分析框架图 (Multi-Panel Comprehensive Analysis Framework)",
    "color_scheme": "Okabe-Ito Academic Standard (Colorblind-Friendly)",
    "aspect_ratio": "16:9",
    "prompt": prompt
}

print(json.dumps([figure], ensure_ascii=False, indent=2))
