#!/usr/bin/env python3
"""Generate the figure prompt JSON."""
import json

prompt = r"""A highly detailed, information-dense academic paper comprehensive analysis framework diagram in the style of top-tier management science and operations research publications. The diagram illustrates the product portfolio analysis based on the Boston Consulting Group (BCG) Matrix methodology, the “3-5-2” strategic realignment plan, packaging optimization comparison, and brand recognition enhancement through regional cultural design integration. The overall layout is arranged as a rich 2×2 four-panel grid with cross-panel connecting arrows forming a complete analytical chain from diagnosis to strategy to implementation to outcome measurement, with all figure labels and annotations rendered in English with Chinese parenthetical translations where the source paper uses Chinese terminology.

=== PANEL A: BCG MATRIX PRODUCT PORTFOLIO ANALYSIS (TOP-LEFT) ===
This panel presents a classic BCG Matrix 2×2 quadrant scatter plot. Set against a very faint grey #F7F7F7 background panel with a small-caps Steel Blue #0072B2 section label “BCG MATRIX ANALYSIS | 波士顿矩阵分析” at the top, separated by a thin grey #CCCCCC horizontal divider line. The horizontal x-axis is labeled “Relative Market Share (Low → High)” and the vertical y-axis is labeled “Industry Growth Rate (Low → High)”, both rendered in Charcoal #333333 small annotation text at size approximately 8pt, with Dark Grey #4D4D4D thin axis lines of 1px weight. The axes intersect at their midpoints, creating the classic four-quadrant structure divided by grey dashed crossing lines. The four quadrants are clearly labeled: top-left quadrant labeled “STARS (明星类) — High Share × High Growth”, top-right quadrant labeled “QUESTION MARKS (问题类) — Low Share × High Growth”, bottom-left quadrant labeled “CASH COWS (金牛类) — High Share × Low Growth”, and bottom-right quadrant labeled “DOGS (瘦狗类) — Low Share × Low Growth”. Each quadrant label is rendered in small-caps Charcoal #333333 text. Each quadrant uses an extremely subtle semi-transparent fill tint to provide visual distinction without overwhelming the data: the Stars zone receives a 5% Warm Orange #E69F00 tint, the Question Marks zone receives a 5% Bluish Green #009E73 tint, while Cash Cows and Dogs zones remain pure white. Within each quadrant, a small monochrome icon thumbnail of approximately 15×15 pixels illustrates the category archetype: the Stars zone contains a small upward-trend arrow icon with a star symbol indicating dual high advantage, the Question Marks zone contains a small stylized question mark icon indicating strategic uncertainty, the Cash Cows zone contains a small stable horizontal bar chart thumbnail indicating steady profit contribution, and the Dogs zone contains a small downward-trend arrow icon with a flag indicating decline. The 42 product units are plotted as small filled-circle scatter points distributed across all four quadrants according to their market share and growth rate values. Stars products are plotted as small Warm Orange #E69F00 circles of 4px diameter, with a compact annotation bubble reading “<15% of total”. Question Marks products are plotted as small Bluish Green #009E73 circles of 4px diameter, with annotation “>30% of total”. Cash Cows products are plotted as Steel Blue #0072B2 circles, and Dogs products as Light Grey #CCCCCC circles. A small data summary annotation box in the bottom-right corner within this panel states in Medium Grey #666666 text at 7pt size: “n = 42 product units | Portfolio imbalance identified: Stars proportion insufficient (<15%), excessive Question Marks burden (>30%)”. The quadrant boundary dashed lines extend slightly beyond the axes with small arrowheads."""

# For brevity in this test, just output the partial prompt
print("Prompt length:", len(prompt))
print("First 200 chars:", prompt[:200])
